<script lang="ts" module>
  import { base } from '$app/paths';
  import { loadKrishnaSvg, type Reaction } from '../mascot/krishna';

  // Static poses live in static/mascot/, generated by scripts/process-mascots.py
  export type MascotMood =
    | 'default'
    | 'cheerful'
    | 'celebrating'
    | 'excited'
    | 'amazed'
    | 'proud'
    | 'affectionate'
    | 'thinking'
    | 'determined'
    | 'mischievous'
    | 'disappointed'
    | 'shocked'
    | 'worried'
    | 'crying'
    | 'puppy';

  /**
   * The moods that have a hand-animated version (the layered SVG, see ../mascot/krishna.ts). `idle` is the resting
   * face. Moods that change the whole pose — shocked, worried, determined, mischievous, puppy — have no animation
   * yet, so they keep showing their static WebP.
   */
  const ANIMATED: Partial<Record<MascotMood, Reaction | 'idle'>> = {
    default: 'idle',
    cheerful: 'correct',
    proud: 'correct',
    excited: 'combo',
    amazed: 'combo',
    celebrating: 'celebrate',
    affectionate: 'love',
    thinking: 'think',
    disappointed: 'wrong',
    crying: 'heartbreak'
  };

  const srcFor = (mood: MascotMood) => `${base}/mascot/${mood}.webp`;

  /** Warm the cache so a mood swap mid-exercise doesn't flash blank while the new pose loads. */
  export function preloadMascots(moods: MascotMood[]) {
    if (typeof Image === 'undefined') return;
    for (const mood of moods) new Image().src = srcFor(mood);
    // The animated SVG is a separate chunk; start fetching it too
    loadKrishnaSvg().catch(() => {});
  }
</script>

<script lang="ts">
  import { onMount } from 'svelte';
  import { mountKrishna, type Krishna } from '../mascot/krishna';

  let {
    mood = 'default',
    size = 'md',
    animate = false
  } = $props<{
    mood?: MascotMood;
    size?: 'sm' | 'md' | 'lg' | 'xl';
    /** Bounces the static pose; the animated mascot already moves on its own */
    animate?: boolean;
  }>();

  const sizeClasses = {
    sm: 'w-14 h-14',
    md: 'w-20 h-20',
    lg: 'w-28 h-28',
    xl: 'w-44 h-44'
  } as const;

  let host = $state<HTMLDivElement>();
  let krishna: Krishna | null = null;
  // Becomes true once the SVG chunk has loaded and been mounted; until then (and for readers who ask for
  // reduced motion) the static WebP stands in
  let ready = $state(false);

  onMount(() => {
    if (matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    let cancelled = false;
    loadKrishnaSvg()
      .then((markup) => {
        if (cancelled || !host) return;
        krishna = mountKrishna(host, markup);
        ready = true;
      })
      .catch(() => {});
    return () => {
      cancelled = true;
      krishna?.destroy();
      krishna = null;
    };
  });

  const reaction = $derived(ANIMATED[mood as MascotMood]);
  // Animated moods show the SVG; the rest show their static pose on top of it
  const showSvg = $derived(ready && reaction !== undefined);

  // A change of mood plays that mood's reaction (or settles back to the resting face)
  $effect(() => {
    if (!ready || !krishna || reaction === undefined) return;
    if (reaction === 'idle') krishna.rest();
    else krishna.react(reaction);
  });
</script>

<div class="relative {sizeClasses[size as keyof typeof sizeClasses]} select-none shrink-0" aria-hidden="true">
  {#if !showSvg}
    <div class="absolute bottom-[1%] left-1/2 -translate-x-1/2 w-1/2 h-[7%] rounded-[50%] bg-text-primary/15 blur-[1px]"></div>
  {/if}
  <div class="relative w-full h-full {animate && !showSvg ? 'animate-mascot-bounce' : ''}">
    <!-- The SVG stays mounted so its idle motion and expression carry across moods; the static pose covers it when needed -->
    <div bind:this={host} class="absolute inset-0" style:visibility={showSvg ? 'visible' : 'hidden'}></div>
    {#if !showSvg}
      <!-- Re-keyed per mood so every reaction pops in, like Duolingo's characters -->
      {#key mood}
        <img
          src={srcFor(mood)}
          alt=""
          width="480"
          height="480"
          draggable="false"
          class="relative w-full h-full object-contain animate-pop-in"
        />
      {/key}
    {/if}
  </div>
</div>
