<script lang="ts" module>
  import { base } from '$app/paths';

  // Files live in static/mascot/, generated by scripts/process-mascots.py
  export type MascotMood =
    | 'default'
    | 'cheerful'
    | 'celebrating'
    | 'excited'
    | 'amazed'
    | 'proud'
    | 'affectionate'
    | 'thinking'
    | 'determined'
    | 'mischievous'
    | 'disappointed'
    | 'shocked'
    | 'worried'
    | 'crying'
    | 'puppy';

  const srcFor = (mood: MascotMood) => `${base}/mascot/${mood}.webp`;

  /** Warm the cache so a mood swap mid-exercise doesn't flash blank while the new pose loads. */
  export function preloadMascots(moods: MascotMood[]) {
    if (typeof Image === 'undefined') return;
    for (const mood of moods) new Image().src = srcFor(mood);
  }
</script>

<script lang="ts">
  let {
    mood = 'default',
    size = 'md',
    animate = false
  } = $props<{
    mood?: MascotMood;
    size?: 'sm' | 'md' | 'lg' | 'xl';
    animate?: boolean;
  }>();

  const sizeClasses = {
    sm: 'w-14 h-14',
    md: 'w-20 h-20',
    lg: 'w-28 h-28',
    xl: 'w-44 h-44'
  } as const;
</script>

<div class="relative {sizeClasses[size as keyof typeof sizeClasses]} select-none shrink-0" aria-hidden="true">
  <div class="absolute bottom-[1%] left-1/2 -translate-x-1/2 w-1/2 h-[7%] rounded-[50%] bg-text-primary/15 blur-[1px]"></div>
  <div class="relative w-full h-full {animate ? 'animate-mascot-bounce' : ''}">
    <!-- Re-keyed per mood so every reaction pops in, like Duolingo's characters -->
    {#key mood}
      <img
        src={srcFor(mood)}
        alt=""
        width="480"
        height="480"
        draggable="false"
        class="w-full h-full object-contain animate-pop-in"
      />
    {/key}
  </div>
</div>
